name: Pull Request Check
on: [pull_request, workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Solution_to_Algebra_Chapter_0.tex
